apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: my-app
spec:
  rules:
  - host: mynodeapp.com
    http:
      paths:
      - path: /nodeapp
        pathType: Prefix
        backend:
          service:
            name: node-app-service
            port:
              number: 8080
      - path: /mongo-express
        pathType: Prefix
        backend:
          service:
            name: mongo-express-service
            port:
              number: 8081
