apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress

spec:
  rules:
  - host: mynodeapp.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-app-service
            port:
              number: 8080
